name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Setting the environment up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: |
        sudo dscl . -create /Users/vncuser
        sudo dscl . -create /Users/vncuser UserShell /bin/bash
        sudo dscl . -create /Users/vncuser RealName "VNC User"
        sudo dscl . -create /Users/vncuser UniqueID 1001
        sudo dscl . -create /Users/vncuser PrimaryGroupID 80
        sudo dscl . -create /Users/vncuser NFSHomeDirectory /Users/vncuser
        sudo dscl . -passwd /Users/vncuser $VNC_USER_PASSWORD
        sudo dscl . -passwd /Users/vncuser $VNC_USER_PASSWORD
        sudo createhomedir -c -u vncuser > /dev/null
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
        brew install --cask ngrok
        ngrok authtoken $NGROK_AUTH_TOKEN
    - name: Create Tunnel
      run: ngrok tcp --region=eu 5900
